name: no-confusion
description: Check text files against Unicode impostor symbols that look like regular ASCII.
author: Athenian
inputs:
  include:
    description: List of file globs to check, JSON string.
    default: "[]"
    required: false
  exclude_patterns:
    description: Map of file globs to corresponding regular expressions that should be ignored, JSON object string.
    default: "{}"
    required: false
  exclude:
    description: List of file globs to exclude, JSON string.
    default: "[]"
    required: false
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set -x
      python3 ${{ github.action_path }}/main.py --include '${{ inputs.include }}' --exclude-patterns '${{ inputs.exclude_patterns }}' --exclude '${{ inputs.exclude }}'
branding:
  color: purple
  icon: bar-chart-2
